### ISSUE TITLE
No App Found

### ISSUE THREAD

**Issue by gee455** [nphivu414/ai-fusion-kit#13]
Hey, amazing work first of all. Not sure if you're still supporting this project but @nphivu414 @toproad1407 but whenever I run the app I get an error saying "No App Found" after I do any user sign up/sign in. 

Also, when I run the SQL code snippet I had to make sure to create the public.message_role, role before hand and match it to the roles in the code. 

Any chance that has to do with the issue I'm facing or any tips on what I might be doing wrong?

Thanks so much!

<img width="573" alt="Screen Shot 2024-02-19 at 9 08 28 AM" src="https://github.com/nphivu414/ai-fusion-kit/assets/1879581/7c7de225-b7b8-4286-ae74-541fdf791a7e">

**Comment by nphivu414** [comment]
hi @gee455 , thanks for checking out the repo

You can try to add a new record to the `apps` table using the following data to resolve the issue:

```
name: "GPT AI Assistant"
slug: "/apps/chat"
logoUrl: "/_next/static/media/chat-gpt.2fe64c6b.jpeg"
```

**Comment by gee455** [comment]
Amazing thank you for the prompt reply! The slug was what I was missing.
Thanks again and keep up the amazing work!

Thanks,

Calvin Gee

Sent via Superhuman ***@***.***>
